port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxies:
  - {name: Trojan01, server: dynamic-sg2b.obfs.xyz, port: 443, type: vmess, uuid: f7b21150-e374-49af-b7c3-6cc57830d79a, sni: m.facebook.com, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /fastssh, headers: {Host: m.facebook.com}}}
  - {name: Trojan02, server: dynamic-us2b.obfs.xyz, port: 443, type: vmess, uuid: ded97838-136d-45f2-8017-67203c0a88fa, sni: m.facebook.com, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /fastssh, headers: {Host: m.facebook.com}}}
  - {name: Trojan03, server: dynamic-sg1b.obfs.xyz, port: 443, type: vmess, uuid: 4b2fac23-21a2-4e94-8998-7b62376de631, sni: m.facebook.com, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /fastssh, headers: {Host: m.facebook.com}}}
  - {name: Trojan04, server: dynamic-us1b.obfs.xyz, port: 443, type: vmess, uuid: f5cfb241-c3ca-4b37-ad0a-528f812fe17b, sni: m.facebook.com, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /fastssh, headers: {Host: m.facebook.com}}}
  - {name: Trojan05, server: de.tjvpn.org, port: 443, udp: true, type: trojan, password: 64463e90-f10c-11ec-b931-225401db9d57, sni: m.facebook.com, skip-cert-verify: true}
  - {name: Trojan06, server: fr-1.tjvpn.org, port: 443, udp: true, type: trojan, password: 7b5050b0-f10c-11ec-b539-225401db9d57, sni: m.facebook.com, skip-cert-verify: true}
  - {name: Trojan07, server: ca.tjvpn.org, port: 443, udp: true, type: trojan, password: 932285b0-f10c-11ec-b533-225401db9d57, sni: m.facebook.com, skip-cert-verify: true}
  - {name: Trojan08, server: sg-ovh.tjvpn.org, port: 443, udp: true, type: trojan, password: d14f5a40-f10c-11ec-b039-225401db9d57, sni: m.facebook.com, skip-cert-verify: true}
  - {name: Trojan09, server: sghe.tjvpn.org, port: 443, udp: true, type: trojan, password: ebcc3260-f10c-11ec-b639-225401db9d57, sni: m.facebook.com, skip-cert-verify: true}
  - {name: Trojan10, server: id-1.tjvpn.org, port: 443, udp: true, type: trojan, password: 0692ca40-f10d-11ec-b735-225401db9d57, sni: m.facebook.com, skip-cert-verify: true}

proxy-groups:
  - name: nushan-kodikara-clash
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - Trojan01
      - Trojan02
      - Trojan03
      - Trojan04
      - Trojan05
      - Trojan06
      - Trojan07
      - Trojan08
      - Trojan09
      - Trojan10

rules:
 - MATCH,nushan-kodikara-clash
